### ISSUE TITLE
maybe add multiplayer

### ISSUE THREAD

**Issue by derekchai** [BeefStew34/Chess-JavaFX#2]
it would be cool i want to play wiwith h mwith my freineds ![image](https://github.com/user-attachments/assets/03210e77-3f07-494f-841f-84c62c21ae56)

**Comment by derekchai** [comment]
omg cute cat

**Comment by BeefStew34** [comment]
Nice cat
Multiplayer is now supported on port 4444
Untested outside of 127.0.0.1 tho
